version: 1
concurrency: 2

# Environment variables for this target
env:
  HTTPX_MAX_HOSTS: "150"
  SUBFINDER_MAX_TIME: "30m"

# Template variables
vars:
  TARGET: "example.com"  # Will be overridden by CLI argument

# Pipeline definition with dependencies
pipeline:
  # ========================================
  # BASIC RECONNAISSANCE PIPELINE
  # ========================================
  
  # Step 1: Subdomain enumeration and HTTP probing
  - name: subfinder_httpx
    desc: "Subdomain enumeration with subfinder and HTTP probing"
    cmd: |
      subfinder -d {TARGET} -recursive | httpx -o {OUT}/outputs/recon/alive_subdomains.txt
    timeout: 1800

  # Step 2: Technology stack detection
  - name: tech_stack
    desc: "Technology stack detection on alive subdomains"
    needs: [subfinder_httpx]
    cmd: |
      cat {OUT}/outputs/recon/alive_subdomains.txt | httpx -title -sc -tech-detect -o {OUT}/outputs/web/tech_stack.txt
    timeout: 1200

  # Step 3: JavaScript file discovery
  - name: js_discovery
    desc: "JavaScript file discovery with katana"
    needs: [subfinder_httpx]
    cmd: |
      cat {OUT}/outputs/recon/alive_subdomains.txt | katana -depth 3 -rl 2 | grep -e .js | httpx -nc 200 >> {OUT}/outputs/endpoints/alive_jsfile.txt
    timeout: 2400

  # Step 4: Nuclei scanning for tokens and exposures
  - name: nuclei_tokens
    desc: "Nuclei scanning for tokens and exposures in JS files"
    needs: [js_discovery]
    cmd: |
      nuclei -l {OUT}/outputs/endpoints/alive_jsfile.txt -tags token,exposure -o {OUT}/outputs/scans/nuclei_tokens.json
    timeout: 1800

  # Generate summary report
  - name: summarize
    desc: "Generate analysis summary and reports"
    needs: [nuclei_tokens, tech_stack]
    kind: internal:summarize

# ========================================
# ADDITIONAL STEPS (Uncomment as needed)
# ========================================

# Additional subdomain enumeration
# - name: amass_passive
#   desc: "Passive subdomain enumeration with amass"
#   cmd: |
#     amass enum -passive -d {TARGET} -o {OUT}/outputs/recon/amass.txt
#   timeout: 2400

# Wayback machine endpoint discovery
# - name: waybackurls
#   desc: "Historical endpoint discovery with waybackurls"
#   needs: [subfinder_httpx]
#   cmd: |
#     cat {OUT}/outputs/recon/alive_subdomains.txt | waybackurls > {OUT}/outputs/endpoints/waybackurls.txt
#   timeout: 1800

# Parameter discovery
# - name: paramspider
#   desc: "Parameter discovery with paramspider"
#   needs: [subfinder_httpx]
#   cmd: |
#     cd {OUT}/outputs/endpoints/ && \
#     cat ../recon/alive_subdomains.txt | while read domain; do \
#       paramspider -d "$domain" --exclude png,jpg,jpeg,gif,svg,ico,css,js,woff,woff2,ttf --level high -o paramspider_"$domain".txt || true; \
#     done
#   timeout: 2400

# Port scanning
# - name: naabu_ports
#   desc: "Port scanning with naabu"
#   needs: [subfinder_httpx]
#   cmd: |
#     naabu -list {OUT}/outputs/recon/alive_subdomains.txt -top-ports 1000 -o {OUT}/outputs/scans/naabu_ports.txt
#   timeout: 1800

# Screenshots
# - name: gowitness
#   desc: "Screenshot capture with gowitness"
#   needs: [subfinder_httpx]
#   cmd: |
#     cat {OUT}/outputs/recon/alive_subdomains.txt | gowitness file -f - --screenshot-path {OUT}/outputs/web/screenshots
#   timeout: 1800